{{- if eq .Values.sumologic.traces.enabled true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-otelcol" (include "sumologic.name" .) }}
  labels:
    app: {{ printf "%s-otelcol" (include "sumologic.labels.app" .) }}
    {{- include "sumologic.labels.common" . | nindent 4 }}
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: {{ .Values.otelcolDeployment.replicas }}
  selector:
    matchLabels:
      app: {{ printf "%s-otelcol" (include "sumologic.labels.app" .) }}
  template:
    metadata:
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8888"
        prometheus.io/scrape: "true"
      labels:
        app: {{ printf "%s-otelcol" (include "sumologic.labels.app" .) }}
        {{- include "sumologic.labels.common" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "sumologic.fullname" . }}
      {{- if .Values.otelcolDeployment.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.otelcolDeployment.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.otelcolDeployment.tolerations }}
      tolerations:
        {{ toYaml .Values.otelcolDeployment.tolerations | indent 8 }}
      {{- end }}
      containers:
      - name: otelcontrib-collector
        image: {{ .Values.otelcolDeployment.image.name }}:{{ .Values.otelcolDeployment.image.tag }}
        imagePullPolicy: {{ .Values.otelcolDeployment.image.pullPolicy }}
        command:
          - "/otelcontribcol"
          - "--config=/conf/traces.otelcol.conf.yaml"
          - {{ printf "--mem-ballast-size-mib=%s" .Values.otelcolDeployment.memBallastSizeMib }}
        env:
        - name: GOGC
          value: "80"
        resources:
          {{- toYaml .Values.otelcolDeployment.resources | nindent 10 }}
        ports:
        - containerPort: 55678 # Default endpoint for Opencensus receiver.
        - containerPort: 14267 # Default endpoint for Jaeger TChannel receiver.
        - containerPort: 14268 # Default endpoint for Jaeger HTTP receiver.
        - containerPort: 14250 # Default endpoint for Jaeger gRPC receiver.
        - containerPort: 9411 # Default endpoint for Zipkin receiver.
        - containerPort: 8888  # Default endpoint for querying metrics.
        volumeMounts:
        - name: otel-collector-config-vol
          mountPath: /conf
        livenessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
        readinessProbe:
          httpGet:
            path: /
            port: 13133 # Health Check extension default port.
      volumes:
        - configMap:
            name: {{ printf "%s-otelcol" (include "sumologic.name" .) }}
          name: otel-collector-config-vol
{{- end }}
