{{- if eq .Values.sumologic.traces.enable true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-otelcol" (include "sumologic.name" .) }}
  labels:
    app: {{ printf "%s-otelcol" (include "sumologic.labels.app" .) }}
    {{- include "sumologic.labels.common" . | nindent 4 }}
data:
  {{- (tpl (.Files.Glob "conf/traces/traces.otelcol.conf.yaml").AsConfig .) | nindent 2 }}
{{- end }}